remote_controller:
  type: joystick
  available_mode: all
lms151:
  type: lidar
  available_mode: none
septentrio:
  type: gps
  available_mode: all
xsens:
  type: imu
  available_mode: all
axis:
  type: camera
  available_mode: none
zed1:
  type: stereo_camera
  available_mode: none
realsense:
  type: rgbd_camera
  available_mode: none
